### ISSUE TITLE
Font Awesome Error

### ISSUE THREAD

**Issue by omoju** [bmschmidt/CV-pandoc-healy#1]
I am trying to `make` your code, so I can use it for my CV. But run into the error below. Where should I put font awesome to make things work.

kpathsea: Running mktexmf FontAwesome
! I can't find file `FontAwesome'.
<*> ...our; mag:=1; nonstopmode; input FontAwesome

Please type another input file name
! Emergency stop.
<*> ...our; mag:=1; nonstopmode; input FontAwesome

Transcript written on mfput.log.
grep: FontAwesome.log: No such file or directory
mktextfm: `mf-nowin -progname=mf \mode:=ljfour; mag:=1; nonstopmode; input FontAwesome' failed to make FontAwesome.tfm.
kpathsea: Appending font creation commands to missfont.log.

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
!
! fontspec error: "font-not-found"
! 
! The font "FontAwesome" cannot be found.
! 
! See the fontspec documentation for further information.
! 
! For immediate help type H <return>.
!...............................................

**Comment by bmschmidt** [comment]
Font installation probably varies by operating system; on OS X, I downloaded the fontawesome files from here https://fortawesome.github.io/Font-Awesome/, navigated to fonts in the folder, and just double-clicked on the .otf file which prepared the installation.

**Comment by omoju** [comment]
Thanks. I also think it has to do with my system configured for pdflatex instead of XeLaTeX.
Will install the fonts and see.

**Comment by omoju** [comment]
Not sure how I finally resolved this. Closing this issue because it is now stale.
