### ISSUE TITLE
YAML error

### ISSUE THREAD

**Issue by fustkilas** [bmschmidt/CV-pandoc-healy#5]
on running ```make``` on a freshly cloned repo i get:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named yaml
make: *** [validate_yaml] Error 1
```

I have pip3, Python 2.7.10, and Mac OS X 10.14.6.

Any advice appreciated.

**Comment by bmschmidt** [comment]
Mostly likely, you need to run `pip install pyyaml` or `pip3 install pyyaml`, depending on whether your python simlinks to python 2 or 3.

But you  can safely delete the lines from the Makefile that call this ([here](
https://github.com/bmschmidt/CV-pandoc-healy/blob/master/Makefile#L5-L6)); python is used only to double-check the YAML file, and nothing bad will happen  if the YAML is indeed (the last one YAML file might not (!) have been, but I just pushed an update)
